---
resources:
- name: cf-cpi-pipelines
  type: git
  source:
    uri: git@github.com:leifei87/cf-cpi-pipelines.git
    branch: master
    private_key: {{git_private_key}}

jobs:
- name: cpi-runner
  serial: true
  plan:
  - get: cf-cpi-pipelines
  - task: create-infrastructure
    file: cf-cpi-pipelines/tasks/create-infrastructure/task.yml
    params:
      SUBSCRIPTION_ID: {{subscription_id}}
      TENANT_ID: {{tenant_id}}
      CLIENT_ID: {{client_id}}
      CLIENT_SECRET: {{client_secret}}
      REGION: {{region}}
      RESOURCE_GROUP_PREFIX: {{resource_group_prefix}}
      BOSH_SECURITY_GROUP: {{bosh_security_group}}
      CF_SECURITY_GROUP: {{cf_security_group}}
      VNET_NAME: {{vnet_name}}
      BOSH_SUBNET_NAME: {{bosh_subnet_name}}
      CF_SUBNET_NAME: {{cf_subnet_name}}
      VNETWORK_CIDR: {{network_cidr}}
      BOSH_SUBNET_CIDR: {{bosh_subnet_cidr}}
      CF_SUBNET_CIDR: {{cf_subnet_cidr}}

  - task: bosh-deploy
    file: cf-cpi-pipelines/tasks/bosh-deploy/task.yml
    params:
      SUBSCRIPTION_ID: {{subscription_id}}
      TENANT_ID: {{tenant_id}}
      CLIENT_ID: {{client_id}}
      CLIENT_SECRET: {{client_secret}}
      ENVIRONMENT: {{environment}}
      REGION: {{region}}
      RESOURCE_GROUP_PREFIX: {{resource_group_prefix}}
      BOSH_SECURITY_GROUP: {{bosh_security_group}}
      CF_SECURITY_GROUP: {{cf_security_group}}
      VNET_NAME: {{vnet_name}}
      BOSH_SUBNET_NAME: {{bosh_subnet_name}}
      CF_SUBNET_NAME: {{cf_subnet_name}}
      VNETWORK_CIDR: {{network_cidr}}
      BOSH_SUBNET_CIDR: {{bosh_subnet_cidr}}
      CF_SUBNET_CIDR: {{cf_subnet_cidr}}
      BOSH_PRIVATE_IP: {{bosh_private_ip}}
      BOSH_GATEWAY: {{bosh_gateway}}
      INSTANCE_TYPE: {{instance_type}}