---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
  - name: cf-cpi-pipelines
outputs:
  - name: bosh-director-cert
run:
  path: cf-cpi-pipelines/tasks/bosh-deploy/task.sh

params:
  AZURE_SUBSCRIPTION_ID:
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
