---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
  - name: cf-cpi-pipelines
  - name: terraform-state
outputs:
  - name: vars
run:
  path: cf-cpi-pipelines/tasks/bosh-deploy/task.sh

params:
  SUBSCRIPTION_ID:
  TENANT_ID:
  CLIENT_ID:
  CLIENT_SECRET:
  ENVIRONMENT:
  REGION:
  RESOURCE_GROUP_PREFIX:
  BOSH_SECURITY_GROUP:
  CF_SECURITY_GROUP:
  VNET_NAME:
  BOSH_SUBNET_NAME:
  CF_SUBNET_NAME:
  VNETWORK_CIDR:
  BOSH_SUBNET_CIDR:
  CF_SUBNET_CIDR:
  BOSH_PRIVATE_IP:
  BOSH_GATEWAY:
